"""
Módulo de Configuração
======================

Carrega as variáveis de ambiente com fallbacks padronizados para o ambiente do Plone 6.
"""

import os

# URL base da API REST do Plone 6
API_URL: str = os.getenv("API_URL", "https://www.gov.br/studyinbrazil")

# Token de Autenticação JWT
API_TOKEN: str = os.getenv("API_TOKEN", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMzM3NDIzOTYzMyIsImV4cCI6MTc4NTAzMTc1NiwiZnVsbG5hbWUiOiJNQVlMT04gTUFSVElOUyBERSBNRUxPIiwibG9naW51bmljb190b2tlbiI6ImV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUp6ZFdJaU9pSXhNek0zTkRJek9UWXpNeUlzSW1WdFlXbHNYM1psY21sbWFXVmtJam9pZEhKMVpTSXNJbUZ0Y2lJNld5SndZWE56ZDJRaUxDSmpZWEIwWTJoaElpd2liV1poSWl3aWIzUndYMjltWm14cGJtVWlYU3dpY0hKdlptbHNaU0k2SW1oMGRIQnpPaTh2YzJWeWRtbGpiM011WVdObGMzTnZMbWR2ZGk1aWNpOGlMQ0pyYVdRaU9pSnljMkV4SWl3aWFYTnpJam9pYUhSMGNITTZMeTl6YzI4dVlXTmxjM052TG1kdmRpNWljaThpTENKd2FHOXVaVjl1ZFcxaVpYSmZkbVZ5YVdacFpXUWlPaUowY25WbElpd2ljSEpsWm1WeWNtVmtYM1Z6WlhKdVlXMWxJam9pTVRNek56UXlNemsyTXpNaUxDSnViMjVqWlNJNklqTmxNREF3T0dVNE9XWTNaQ0lzSW5CcFkzUjFjbVVpT2lKb2RIUndjem92TDNOemJ5NWhZMlZ6YzI4dVoyOTJMbUp5TDNWelpYSnBibVp2TDNCcFkzUjFjbVVpTENKaGRXUWlPaUpuYjNaaWNpSXNJbUYxZEdoZmRHbHRaU0k2TVRjNE5UQXlPREUxTlN3aWMyTnZjR1VpT2xzaWNHaHZibVVpTENKdmNHVnVhV1FpTENKbmIzWmljbDlqYjI1bWFXRmlhV3hwWkdGa1pYTWlMQ0p3Y205bWFXeGxJaXdpWlcxaGFXd2lYU3dpYm1GdFpTSTZJazFCV1V4UFRpQk5RVkpVU1U1VElFUkZJRTFGVEU4aUxDSndhRzl1WlY5dWRXMWlaWElpT2lJek5UazVNakl4TnpRMU9TSXNJbVY0Y0NJNk1UYzROVEF5T0RjMU5pd2lhV0YwSWpveE56ZzFNREk0TVRVMkxDSnFkR2tpT2lJM01qWXhZamt4WXkwellqa3hMVFJrTldRdE9XTXhaUzB5TXpoak0yTTBNR1ZoTlRjaUxDSmxiV0ZwYkNJNkltMWhlV3h2Ym0xaGNuUnBibk13TjBCbmJXRnBiQzVqYjIwaWZRLk9TcXg3WGt1Sm1mdUVQRk5BTGp2dHR0YzNnSjlSMm0tS0IyaFpNQ1lEX28ifQ.406jgfZhnN6dRuJ3zMkIIJ_xKi58VfySIgTjQ5dRUtg")

# Credenciais de Login (opcionais para autenticação via /@login)
API_USERNAME: str = os.getenv("API_USERNAME", "")
API_PASSWORD: str = os.getenv("API_PASSWORD", "")

# Caminho para a planilha de dados de IES
EXCEL_PATH: str = os.getenv("EXCEL_PATH", "studyinbr/lista_ies_completa.csv")
